---
logging:
  level:
    org.springframework: ERROR
    org.reyabreu.demo: INFO
regex: "^([Gg][Ii][Rr]\\s*0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9]?[A-Za-z]))))\\s*[0-9][A-Za-z]{2})$"
api:
  postcodes:
    baseUri: "https://api.postcodes.io/postcodes/"
    paths:
      lookup: "{postcode}"      
      validate: "{postcode}/validate"
      nearest: "{postcode}/nearest"
spring:
  profiles:
    active:
    - prod
    